Algoritmo "Aula06-01-Descobrir-Idade"
// Algoritmo para calcular a idade de uma pessoa.

Var
anoAtual, anoNasc, idade: inteiro

Inicio

escreva ("Em que anos nos estamos? ")
leia (anoAtual)
escreva ("Em que ano voce nasceu? ")
leia (anoNasc)
idade <- anoAtual - anoNasc
escreval ("Se voce nasceu em", anoNasc, " e nos estamos em", anoAtual, "...")
escreva ("Entao voce tem ", idade, " de idade, nao e?")

Fimalgoritmo