Algoritmo "Passo-09-Exe-086"
// Crie um programa que tenha um procedimento Gerador() que, quando chamado,
// mostre a mensagem "Ola, Mundo!" com algum componente visual (linhas)
// Ex: Ao chamar Gerador() aparece:
// +------=======------+
//      Ola, Mundo!
// +------=======------+

Var

procedimento gerador()
inicio
escreval ()
escreval ("+-------========-------+")
escreval ("       Ola, Mundo!      ")
escreval ("+-------========-------+")
fimprocedimento

Inicio

gerador()

Fimalgoritmo