Algoritmo "Passo-01-Exe-007"
// Algoritmo para ler um número real e mostrar na tela o seu dobro e a sua
// terça parte.

Var
numero, dobro, terca: real

Inicio

escreva ("Digite um número real (x.x): ")
leia (numero)
dobro <- numero * 2
// Para calcular a terça parte de um número basta dividir o número por 3:
terca <- numero / 3
escreval ("O dobro de", numero, " é", dobro)
escreva ("A terça parte de", numero, " é igual a: ", terca:5:4)

Fimalgoritmo