Algoritmo "Passo-01-Exe-007"
// Algoritmo para ler um numero real e mostrar na tela o seu dobro e a sua
// terca parte.

Var
numero, dobro, terca: real

Inicio

escreva ("Digite um numero real (x.x): ")
leia (numero)
dobro <- numero * 2
// Para calcular a terca parte de um numero basta dividir o numero por 3:
terca <- numero / 3
escreval ("O dobro de", numero, " e", dobro)
escreva ("A terca parte de", numero, " e igual a: ", terca:5:4)

Fimalgoritmo