Algoritmo "aula12-02-somar"
// Algoritmo para somar dois numeros dentro de um procedimento onde a passagem
// de parametro se da por valor.

Var
x, y: inteiro


// PROCEDIMENTO
procedimento soma(x2, y2: inteiro)
inicio
escreval("recebi o valor ", x2)
escreval("recebi o valor ", y2)
escreval("A soma entre os dois numeros e:", x2 + y2)
fimprocedimento


// PROGRAMA PRINCIPAL
Inicio

x <- 5
y <- 3
soma (x, y)

Fimalgoritmo