Algoritmo "Aula03-03-Media"
// Algoritmo para calcular a media entre dois valores.

Var
numero1, numero2: inteiro
media: real

Inicio

escreva ("Digite um numero: ")
leia (numero1)
escreva ("Digite outro numero: ")
leia (numero2)
media <- (numero1 + numero2) / 2
escreval ("===== RESULTADO =====")
escreval ("O primeiro numero foi", numero1)
escreval ("O segundo foi", numero2)
escreval ("A media entre os dois valores e:", media)
escreva ("======================")

Fimalgoritmo